import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Modal from "./components/Modal";
import CreateUserForm from "./components/CreateUserForm";

declare global {
  interface Window {
    createModal: {
      showModal: () => void;
      close: () => void;
    };
  }
}

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <main className="py-6 flex min-h-screen bg-gray-100 flex-col">
          <Modal id="createModal" body={<CreateUserForm />} />
          <h1 className="font-bold text-3xl text-center">Rest API in NextJS</h1>
          {children}
        </main>
      </body>
    </html>
  );
}
